# This file was added for TechDocs with Unity Backstage https://docs.unityops.net/unity-backstage/users/techdocs/
# For more information on the configuration below see https://www.mkdocs.org/user-guide/configuration/
site_name: unity-gaming-services-cli
repo_url: https://github.com/Unity-Technologies/unity-gaming-services-cli
repo_name: GitHub
docs_dir: docs
edit_uri: "edit/main/docs/"
strict: true
plugins:
  - techdocs-core
nav:
  - About TechDocs: "index.md"
  - Introduction to unity-gaming-services-cli: "intro.md"
  - Architecture and design: "design.md"
  - Installing for local development: "installation.md"
  - Troubleshooting: "troubleshooting.md"
  - Runbook: "runbook.md"
